# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 08:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_cards_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cards_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
