# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
